### ISSUE TITLE
Outdated CSS classes?

### ISSUE THREAD

**Issue by benjaminrancourt** [TryGhost/gscan#517]
In my Ghost theme, I disabled the generation of `callout` cards as I made my own CSS implementation for this component.

```json
{
  "config": {
    "card_assets": {
      "exclude": [
        "callout"
      ]
    }
  }
}
```

However, by doing this, `gscan` gives me several warnings despite the fact that I am using exactly the same classes as the [current implementation](https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/frontend/src/cards/css/callout.css) of `kg-callout-card`.

```
- Warning: The .kg-callout-card-background-grey CSS class is required to appear styled in your theme
Affected Files: styles

- Warning: The .kg-callout-card-background-white CSS class is required to appear styled in your theme
Affected Files: styles

- Warning: The .kg-callout-card-background-blue CSS class is required to appear styled in your theme
Affected Files: styles
```

```css
/*
  https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/frontend/src/cards/css/callout.css
 */
.kg-callout-card {
  background-color: color-mix(in srgb, transparent, var(--background-color) 12%);
  border-radius: 3px;
  display: flex;
  padding: 1em 1.5em;

  & div.kg-callout-emoji {
    font-size: 1.15em;
    line-height: 1.25em;
    padding-right: 0.8em;
  }

  & + .kg-callout-card {
    margin-top: 1em;
  }
}

.kg-callout-card-grey {
  --background-color: #7c8b9a;
}

.kg-callout-card-white {
  --background-color: var(--color-white);
  box-shadow: inset 0 0 0 1px rgba(124, 139, 154, 0.25);
}

.kg-callout-card-blue {
  --background-color: #21ace8;
}

.kg-callout-card-background-green,
.kg-callout-card-green {
  --background-color: #f0a50f;
}

.kg-callout-card-yellow {
  --background-color: #34b743;
}

.kg-callout-card-red {
  --background-color: #d12e2e;
}

.kg-callout-card-pink {
  --background-color: #e147ae;
}

.kg-callout-card-purple {
  --background-color: #8755ec;
}

.kg-callout-card-accent {
  background-color: var(--ghost-accent-color);
  color: var(--color-black);
}

```

**Is it possible that we should update the [CSS classes in the v4.js file](https://github.com/TryGhost/gscan/blob/main/lib/specs/v4.js#L216-L227) to match the current implementation?** If so, let me know, I can probably do this fix if you want.
